### ISSUE TITLE
Keytool from JDK 11 does not work.  And the script dies.

### ISSUE THREAD

**Issue by arnav-bnrj** [codedx/codedx-kubernetes#5]
The script dies without any error message or continuing to completion when cacerts Password is entered. This limitation applies when using JDK11 but works when using JDK 8. I will try to attach screenshots, if possible.

Regards.

**Comment by stevesalas** [comment]
Thanks for the feedback. The prerequisite check now includes checking whether the keytool application is associated with Java 8, and we updated the README and Guided Setup accordingly.
